version: "3"

services:
  rails:
    build: .
    container_name: bench
    image: calvincaulfield/bench
    ports:
      - 3001:3001
    restart: always
    network_mode: "host"
    env_file:
      - env/.env-stage
