version: "3"

services:
  rails:
    build: .
    container_name: bench
    image: calvincaulfield/bench
    ports:
      - 3001:3001
    network_mode: "host"
    environment:
      - RAILS_ENV
      - DB_HOST
      - DB_USER
      - DB_PORT
      - DB_PASSWD
      - BENCH_PORT
      - SECRET_KEY_BASE
      - RAILS_SERVE_STATIC_FILES
